name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Source code branch to deploy'
        required: true
        type: choice
        options:
        - master
        - staging
      target_server:
        description: 'Target deployment server hostname'
        required: true
        type: choice
        options:
        - dohaty-sa.com
        - dohaty-tv.dohaty-sa.com
        - staging.dohaty-sa.com
        - alkhassaid.com

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.2']

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4  # Updated to v4 for Node.js 20 support
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install dependencies (Composer)
        run: composer install

      - name: Install dependencies (NPM)
        run: npm install

      - name: Build production JavaScript
        run: npm run build

      - name: Create archive
        run: |
          timestamp=$(date +%Y%m%d-%H%M%S)
          archive_name="deployment_$timestamp_${{ github.event.inputs.branch }}.tar.gz"
          tar -czvf $archive_name .  # Archive the entire project

      - name: Upload archive via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOYMENT_SERVER_HOST }}
          username: deployer
          key: ${{ secrets.DEPLOYMENT_SERVER_SSH_KEY }}
          script: scp ${{ github.workspace }}/$archive_name deployer@${{ secrets.DEPLOYMENT_SERVER_HOST }}:/home/deployer/deploy/builds

      - name: Execute deploy script on the deployment server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOYMENT_SERVER_HOST }}
          username: deployer
          key: ${{ secrets.DEPLOYMENT_SERVER_SSH_KEY }}
          script: bash /home/deployer/deploy/deploy.sh $archive_name ${{ github.event.inputs.target_server }}

